spring:
  application:
    name: User-Service

  datasource:
      url: jdbc:hsqldb:file:C:/ScraperDB/wsDB
      driver-class-name: org.hsqldb.jdbc.JDBCDriver
      username: test
      password: test
  jpa:
      properties:
        show-sql: true
        format-sql: true
        hibernate:
          dialect: org.hibernate.dialect.HSQLDialect
          hbm2ddl:
            auto: validate

